error if php version is not valid

diff --git a/.github/workflows/auto-trigger.yml b/.github/workflows/auto-trigger.yml
--- a/.github/workflows/auto-trigger.yml
+++ b/.github/workflows/auto-trigger.yml
@@ -28,6 +28,11 @@ jobs:
 
           FINGERPRINT=$(jq -r '.assets | map(.digest + .updated_at) | join(",")' latest.json | sha256sum | awk '{print $1}')
           PHP_VERSION=$(jq -r '.assets[0].name' latest.json | grep -oP 'PHP-\K[0-9]+\.[0-9]+')
+          if [[ -z "$PHP_VERSION" || !"$PHP_VERSION" =~ ^[0-9]+\.[0-9]+$ ]]; then
+           echo "Error: Invalid PHP version"
+           rm latest.json
+           exit 1
+          fi
 
           echo "fingerprint=$FINGERPRINT" >> $GITHUB_OUTPUT
           echo "php_version=$PHP_VERSION" >> $GITHUB_OUTPUT
